name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: setup
      run: |
        yarn install
    - name: test
      run: |
        yarn tsc
        yarn test
        yarn build
    - uses: amondnet/now-deployment@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        zeit-token: ${{ secrets.NOW_DEPLOY_KEY }}
      env:
        CI: true
