name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: setup
      run: |
        yarn install
    - name: test
      run: |
        yarn tsc
        yarn test
      env:
        CI: true
    - uses: amondnet/now-deployment@v1
      id: now-deploy
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        zeit-token: ${{ secrets.NOW_DEPLOY_KEY }}
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      id: lighthouseCheck
      uses: foo-software/lighthouse-check-action@master
      with:
        author: ${{ github.actor }}
        branch: ${{ github.ref }}
        outputDirectory: /tmp/artifacts
        urls: ${{ steps.now-deploy.outputs.preview-url }}
        sha: ${{ github.sha }}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
    - name: Handle Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "90"
        minBestPracticesScore: "50"
        minPerformanceScore: "50"
        minProgressiveWebAppScore: "50"
        minSeoScore: "50"
